---
HOSTS:
  centos8:
    platform: el-8-x86_64
    hypervisor: docker
    image: centos:8
    roles:
      - master
      - agent
      - dashboard
      - database
      - classifier
      - default
    docker_cmd: '["/sbin/init"]'
    docker_cap_add:
      - AUDIT_WRITE
    dockeropts:
      Labels:
        one: '1'
        two: '2'
  centos7:
    platform: el-7-x86_64
    hypervisor: docker
    image: centos:7
    roles:
      - agent
    docker_cmd: '/usr/sbin/sshd -D -E /var/log/sshd.log'
    use_image_entrypoint: true
    dockeropts:
      HostConfig:
        Privileged: true
CONFIG:
  nfs_server: none
  consoleport: 443
  log_level: verbose
